version: '3.9'

services:
  server:
    image: my_server
    build: .
    env_file:
      - .env
    ports:
      - 8001:8000
    depends_on:
      - db



  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_DB: lion
      POSTGRES_USER: lion
      POSTGRES_PASSWORD: lion


  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8000